services:
  - type: web
    name: erp-system
    env: python
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
    startCommand: |
      python manage.py migrate && \
      echo "from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.create_superuser('erpadmin', 'admin@example.com', 'yourpassword')" | python manage.py shell && \
      gunicorn erp_system.wsgi:application
